
PRINT CEILING(4.1) -- ARREDONDA VALOR PARA CIMA
PRINT FLOOR(4.1) -- ARREDONADA PARA BAIXO

PRINT RAND() -- GERA VALOR ALEATÓRIO
PRINT ROUND(12.44556, 4)

PRINT POWER(4, 2) -- GERA POTÊNCIA DE UM NÚMERO


