-- INNER JOIN TRAS OS RESULTADOS DE TODAS AS TABELAS

SELECT  C.NomeCompleto,
		C.Cargo,
		C.Contato,
		E.Logradouro, 
		E.Cidade,
		E.Pais
	FROM TB_CLIENTE C
INNER JOIN  TB_ENDERECO E ON C.ClienteId = E.ClienteId

-- LEFT JOIN TODOS OS MEMBROS DA TABELA DA ESQUERDA INDEPENDENTE SE HÁ OU NÃO LIGAÇÃO COM 
-- A TABELA DA DIREITA


-- RIGHT JOIN TUDO A DIREITA DO JOIN INDEPENDENTE SE TEM OU NÃO LIGAÇÃO A TABELA DA ESQUERDA
-- E TRAS SOMENTE O QUE HÁ LIGAÇÃO DA TABELA DA ESQUERDA COM A DA DIREITA

SELECT  C.NomeCompleto,
		C.Cargo,
		C.Contato,
		E.Logradouro, 
		E.Cidade,
		E.Pais
	FROM TB_ENDERECO E
RIGHT JOIN  TB_CLIENTE C 
ON C.ClienteId = E.ClienteId


SELECT * FROM TB_CLIENTE

INSERT INTO TB_CLIENTE (ClienteId, NomeCompleto, Contato, Cargo)
VALUES
('AAAAA','MARCOS ALBERTO','MARIA JOAQUINA','VENDEDOR'),
('BBBBB','MONICA SANTOS','JOSÉ SILVERIA','ATENDENTE'),
('CCCCC','LUANA ALVES','ANA PAULA','PROPRIETÁRIA')


--  UPDATE E DELETE COM JOIN

UPDATE TB_PRODUTO
SET Preco +=1
FROM TB_PRODUTO P
JOIN TB_CATEGORIA C
ON P.CategoriaId = C.CategoriaId
WHERE C.Descricao = 'Condimentos'


SELECT P.Preco FROM TB_PRODUTO P
JOIN TB_CATEGORIA C
ON P.CategoriaId = C.CategoriaId
WHERE C.Descricao = 'Condimentos'


SELECT * FROM TB_PEDIDO P
JOIN TB_FUNCIONARIO F
ON P.FuncionarioId = F.FuncionarioId
JOIN TB_DETALHE_PEDIDO D
ON D.NumeroPedido = P.NumeroPedido
WHERE F.Cargo LIKE 'Vice-Presidente de Vendas'

DELETE TB_PEDIDO FROM TB_PEDIDO P
JOIN TB_FUNCIONARIO F
ON P.FuncionarioId = F.FuncionarioId

WHERE F.Cargo = 'Vice-Presidente de Vendas' AND NumeroPedido = '10265'

DELETE TB_DETALHE_PEDIDO FROM TB_DETALHE_PEDIDO
WHERE NumeroPedido = '10265'








